services:
  app:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    stdin_open: true  # Allow interactive access (for debugging)
    tty: true         # Allocate a pseudo-TTY (for interactive access)
